theme: jekyll-theme-minimal
title: [Vineet Singh]
description:
  [
    Hi Everyone 👋 I'm a software engineer from India constantly learning and growing in the tech world. My expertise includes web technologies like MERN stack JavaScript HTML CSS Node.js and React.js as well as application development in C++ and a bit of Java. For productivity I rely on tools like Neovim for efficiency Tmux for session management and Linux with Hyprland as my window manager & lazygit for git operations. I'm fluent in both English and Hindi. Currently I'm focused on building projects exploring new web technologies and diving into the world of machine learning to expand my skill set. 🚀,
  ]
